package com.project.lunchBooking.model

import java.util.*
import javax.persistence.*
import kotlin.collections.ArrayList

@Entity
data class User(
    // IDENTITY: generated by DB (increasing)
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    var id: Int? = -1,

    @Column
    var username: String,

    @Column
    var password: String,

    @Column
    var email: String,

    @Column
    var verify: Boolean? = false,

    @ManyToMany(fetch = FetchType.EAGER)
    var roles: MutableCollection<Role>? = ArrayList<Role>(),

    @Column(name = "account_non_locked")
    var accountNonLocked: Boolean? = true,

    @Column(name = "failed_attempt")
    var failedAttempt: Int? = 0,

    @Column(name = "lock_time")
    var lockTime: Date? = null



)
